# Generated by Django 4.1.4 on 2022-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.TextField(max_length=4, unique=True)),
                ('store_name', models.TextField()),
                ('store_email', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('message_ID', models.CharField(max_length=40)),
                ('timestamp', models.IntegerField()),
                ('signature', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
